/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App app = new App();

    @Test
    public void QuoteTest() {
        Assertions.assertNotNull(app.getData());
    }
}
