/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.Reader;
import java.lang.reflect.Type;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {
    getData();



    }
    public static Object getData() {
        Object txt = null;
        try {
            // create Gson instance
            Gson gson = new Gson();

            // create a reader
            Reader reader = Files.newBufferedReader(Paths.get("C:/Users/adraf/ASAC/401/quotes/app/src/main/resources/recentquotes.json"));
            Type qoutesListType = new TypeToken<ArrayList<Quotes>>() {
            }.getType();
            List<Quotes> qoutesList = gson.fromJson(reader, qoutesListType);

            // convert JSON array to list of books
            txt = qoutesList.get(getRandomNumber(1, 159));
//            System.out.println(txt);
            quotesData(txt);
            // close reader
            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return txt;
    }

    private static void quotesData(Object list){
        Gson gson = new Gson();

        String jsonOut=gson.toJson(list);

        System.out.println(jsonOut);

        Quotes userObj = gson.fromJson(jsonOut, Quotes.class);
        userObj.getText();
        userObj.getAuthor();


    }

    public static int getRandomNumber(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }
}
